Klara player follow camera
MorranMogge/Stort_spelprojekt pull request #1
Opened 2022-09-19 09:32 UTC by klaand01

Have added the player movement into the player class and need to send it to main

2022-09-20 07:31 UTC, goliver5 requested changes

2022-09-20 07:31 UTC, goliver5 commented on StortSpelProjekt/Game.cpp
> +	playerShape = com.createBoxShape(reactphysics3d::Vector3(5, 5, 5));
gör detta i en klass istället ha inte player react physics 3d variabler i main. exempel en del av arvshierarki.

2022-09-20 07:31 UTC, goliver5 commented on StortSpelProjekt/Game.cpp
> +	//Planet
samma som player

2022-09-20 07:31 UTC, goliver5 commented on StortSpelProjekt/Game.cpp
> +		if (me.GetType() == MouseEvent::EventType::RAW_MOVE)
Hantera mus specifika saker i en egen klass

2022-09-20 07:31 UTC, goliver5 commented on StortSpelProjekt/Game.h
> +	GravityField planetGravityField;
lagra inte react physics variabler i main

2022-09-20 07:31 UTC, goliver5 commented on StortSpelProjekt/Game.h
> +	MouseClass* mouse;
använd en separat klass istället för att lagra i main

2022-09-20 07:31 UTC, goliver5 commented on StortSpelProjekt/GravityField.cpp
> +DirectX::XMFLOAT3 GravityField::calcGravFactor(DirectX::XMFLOAT3 objectPosition)
make another function that takes in a vector of objects and affect them with gravity, so that we dont need to write this function for every object

2022-09-21 09:03 UTC, klaand01 commented on StortSpelProjekt/Game.cpp
> +	playerShape = com.createBoxShape(reactphysics3d::Vector3(5, 5, 5));
@MorranMogge får fixa

2022-09-21 09:03 UTC, klaand01 commented on StortSpelProjekt/Game.cpp
> +	//Planet
@MorranMogge får fixa

2022-09-21 09:03 UTC, klaand01 commented on StortSpelProjekt/Game.h
> +	GravityField planetGravityField;
@MorranMogge får fixa

2022-09-21 10:33 UTC, merged